.TH SOFTWARE-STORE "0.13" "September 2009"

.SH NAME
software-store \- do something

.SH SYNOPSIS
.B software-store [\fIoptions\fR] \fPACKAGE\fR

.SH DESCRIPTION
\fBsoftware-store\fR a graphical interface for package management in Ubuntu.

.SH OPTIONS
Listed below are the command line options for \fBapplication-name\fR:
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-debug\fR
enable debug mode

.SH ENVIRONMENT VARIABLES
.TP
PACKAGE
Opens software-store at the page for PACKAGE

.SH EXAMPLES
.TP
software-store
Opens software-store at the lobby screen.
.TP
application-name gedit.
Opens software-store at the page for the gedit packge.

.SH AUTHOR
\fBapplication-name\fR was written by Michael Vogt <mvo@canonical.com>, and this manual page by Andrew Higginson <rugby471@gmail.com>.

Both are released under the GNU General Public License, version 3 or later.
