#!/usr/bin/python

import logging
import os

from AppCenter.AppCenter import AppCenter


if __name__ == "__main__":
   logging.basicConfig(level=logging.DEBUG)

   if os.path.exists("./data"):
      datadir = "./data"
   else:
      datadir = "/usr/share/app-center/"

   ac = AppCenter(datadir)
   ac.run()

