#!/usr/bin/python
# Copyright (C) 2009 Canonical
#
# Authors:
#  Michael Vogt
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

# thread init is also required otherwise both gst and webkit are unhappy
import pygtk
pygtk.require ("2.0")
import gobject
gobject.threads_init()
import gtk

import gettext
import logging
import os

from softwarecenter.enums import *
from softwarecenter.version import *
from softwarecenter.backend import get_install_backend

from optparse import OptionParser

logger_names = ('softwarecenter','softwarecenter.apt','softwarecenter.backend'
                'softwarecenter.db','softwarecenter.distro','softwarecenter.view',
                'softwarecenter.performance')
if __name__ == "__main__":

    parser = OptionParser("usage: %prog [options] package", 
                          version="%prog "+VERSION)
    parser.add_option("--debug", action="store_true",
                      help="enable debug mode", default=False)
    parser.add_option("--debug-filter", 
                      help="show only specific messages. supported currently: "
                           "'softwarecenter.performance'")
    parser.add_option("--force-rtl", action="store_true",
                      help="force rtl mode (useful for debugging)", 
                      default=False)
    # FIXME:  REMOVE THIS option once launchpad integration is enabled
    #         by default
    parser.add_option("--enable-lp", action="store_true",
                      help="enable launchpad integration (for development use)", 
                      default=False)
    (options, args) = parser.parse_args()
    
    logging.basicConfig()
    logger = logging.getLogger()
    if options.debug_filter:
        log_filter = logging.Filter(options.debug_filter)
        logger.addFilter(log_filter)
        for logger_name in logger_names:
            logging.getLogger(logger_name).addFilter(log_filter)
        # Add filter for backed as it is initialized seperatelly
        get_install_backend()._logger.addFilter(log_filter)
        # implies general debug
        options.debug = True
        
    if options.debug:
        logger.setLevel(logging.DEBUG)
    else:
        logger.setLevel(logging.INFO)
    
    # override text direction for testing purposes
    if options.force_rtl:
        gtk.widget_set_default_direction(gtk.TEXT_DIR_RTL)

    if os.path.exists("./data/ui/SoftwareCenter.ui"):
        logging.getLogger("softwarecenter").info("Using data (UI, xapian) from current dir")
        datadir = "./data"
        xapian_base_path = datadir
    else:
        datadir = "/usr/share/software-center/"
        xapian_base_path = XAPIAN_BASE_PATH
    
    from softwarecenter.app import SoftwareCenterApp
    
    app = SoftwareCenterApp(datadir, xapian_base_path, enable_lp_integration=options.enable_lp)
    # app = SoftwareCenterApp(datadir, xapian_base_path)
    app.run(args)

