#!/usr/bin/python
# Copyright (C) 2009 Canonical
#
# Authors:
#  Michael Vogt
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

import gobject
import logging
import os

from softwarestore.enums import *

from optparse import OptionParser

if __name__ == "__main__":

    parser = OptionParser("usage: %prog [options] package", 
                          version="%prog 0.3.4")
    parser.add_option("--debug", dest="debug", action="store_true",
                      help="enable debug mode", default=False)
    (options, args) = parser.parse_args()

    if options.debug:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)


    #logging.basicConfig(level=logging.DEBUG)
    logging.basicConfig(level=logging.INFO)

    # needed for webkit
    gobject.threads_init()

    if os.path.exists("./data/ui/SoftwareStore.ui"):
        logging.info("Using data (UI, xapian) from current dir")
        datadir = "./data"
        xapian_base_path = datadir
    else:
        datadir = "/usr/share/software-store/"
        xapian_base_path = XAPIAN_BASE_PATH
    
    from softwarestore.app import SoftwareStoreApp
    
    app = SoftwareStoreApp(datadir, xapian_base_path)
    app.run()

