from __future__ import print_function

import unittest


class SoftwareCentertTestResult(unittest.TestResult):

    def startTest(self, test):
        print('\n\n\n==================================================', test)
        super(SoftwareCentertTestResult, self).startTest(test)

    def stopTest(self, test):
        print('==================================================\n\n\n')
        super(SoftwareCentertTestResult, self).stopTest(test)


# Testing frameworks built on top of unittest may want access to the TestResult
# object generated by running a set of tests for reporting purposes; a TestResult
# instance is returned by the TestRunner.run() method for this purpose.


class SoftwareCenterTextTestRunner(unittest.TextTestRunner):

    def __init__(self, *args, **kwargs):
        print('\n*********** SoftwareCenterTextTestRunner before', args, kwargs)
        kwargs['resultclass'] = SoftwareCenterTextTestRunner
        print('\n*********** SoftwareCenterTextTestRunner after', args, kwargs)
        super(SoftwareCenterTextTestRunner, self).__init__(*args, **kwargs)

    #def _makeResult(self):
    #    return SoftwareCentertTestResult()
