#!/usr/bin/python

import apt
import locale
import logging
import os
import sys
import xapian

from ConfigParser import RawConfigParser, NoOptionError
from glob import glob

try:
    from AppCenter.enums import *
except ImportError:
    # support running from the dir too
    d = os.path.dirname(os.path.abspath(os.path.join(os.getcwd(),__file__)))
    sys.path.insert(0, os.path.split(d)[0])
    from AppCenter.enums import *

# weights for the different fields
WEIGHT_DESKTOP_NAME = 10
WEIGHT_DESKTOP_KEYWORD = 5
WEIGHT_DESKTOP_GENERICNAME = 3
WEIGHT_DESKTOP_COMMENT = 1

WEIGHT_APT_SUMMARY = 5
WEIGHT_APT_DESCRIPTION = 1

class DesktopConfigParser(RawConfigParser):
    " thin wrapper that is tailored for xdg Desktop files "
    def get_desktop(self, key):
        " get generic option under 'Desktop Entry'"
        return self.get("Desktop Entry", key)
    def has_option_desktop(self, key):
        " test if there is the option under 'Desktop Entry'"
        return self.has_option("Desktop Entry", key)
    def get_desktop_categories(self):
        " get the list of categories for the desktop file "
        categories = []
        try:
            categories_str = self.get_desktop("Categories")
            for item in categories_str.split(";"):
                if item:
                    categories.append(item)
        except NoOptionError:
            pass
        return categories

def update(db, cache, datadir="/usr/share/app-install/"):
    " index the desktop files in $datadir/desktop/*.desktop "
    term_generator = xapian.TermGenerator()
    for desktopf in glob(datadir+"/desktop/*.desktop"):
        logging.debug("processing %s" % desktopf)
        parser = DesktopConfigParser()
        doc = xapian.Document()
        term_generator.set_document(doc)
        try:
            parser.read(desktopf)
            # app name is the data
            name = parser.get_desktop("Name")
            doc.set_data(name)
            doc.add_term("AA"+name)
            # package name
            pkgname = parser.get_desktop("X-AppInstall-Package")
            doc.add_term("AP"+pkgname)
            doc.add_value(XAPIAN_VALUE_PKGNAME, pkgname)
            archive_section = parser.get_desktop("X-AppInstall-Section")
            doc.add_term("AS"+archive_section)
            doc.add_value(XAPIAN_VALUE_ARCHIVE_SECTION, archive_section)
            if parser.has_option_desktop("Icon"):
                icon = parser.get_desktop("Icon")
                doc.add_value(XAPIAN_VALUE_ICON, icon)
            # write out categories
            for cat in parser.get_desktop_categories():
                doc.add_term("AC"+cat.lower())
            # get type (to distinguish between apps and packages
            if parser.has_option_desktop("Type"):
                type = parser.get_desktop("Type")
                doc.add_term("AT"+type.lower())
            # check gettext domain
            if parser.has_option_desktop("X-Ubuntu-Gettext-Domain"):
                domain = parser.get_desktop("X-Ubuntu-Gettext-Domain")
                doc.add_value(XAPIAN_VALUE_GETTEXT_DOMAIN, domain)
            # architecture
            if parser.has_option_desktop("X-Ubuntu-Architectures"):
                arches = parser.get_desktop("X-Ubuntu-Architectures")
                doc.add_value(XAPIAN_VALUE_ARCHIVE_ARCH, arches)
            # popcon
            if parser.has_option_desktop("X-AppInstall-Popcon"):
                popcon = parser.get_desktop("X-AppInstall-Popcon")
                # sort_by_value uses string compare, so we need to pad here
                doc.add_value(XAPIAN_VALUE_POPCON, 
                              xapian.sortable_serialise(float(popcon)))
            # now add search data from the desktop file
            for key in ["Name","Generic Name","Comment"]:
                if not parser.has_option_desktop(key):
                    continue
                s = parser.get_desktop(key)
                w = globals()["WEIGHT_DESKTOP_"+key.replace(" ","").upper()]
                term_generator.index_text_without_positions(s)
            # add data from the apt cache
            if cache.has_key(pkgname):
                s = cache[pkgname].summary
                term_generator.index_text_without_positions(s, WEIGHT_APT_SUMMARY)
                s = cache[pkgname].description
                term_generator.index_text_without_positions(s, WEIGHT_APT_DESCRIPTION)
            # add our keywords (with high priority)
            if parser.has_option_desktop("X-AppInstall-Keywords"):
                keywords = parser.get_desktop("X-AppInstall-Keywords")
                for s in keywords.split(";"):
                    if s:
                        term_generator.index_text_without_positions(s, WEIGHT_DESKTOP_KEYWORD)
                
            # FIXME: now do the same for the localizations in the
            #        desktop file
            # FIXME3: add X-AppInstall-Section
        except Exception, e:
            logging.warn("error processing: %s %s" % (desktopf, e))
            continue
        # now add it
        db.add_document(doc)
    return True

if __name__ == "__main__":
    #logging.basicConfig(level=logging.DEBUG)
    desktop_base_path = "/usr/share/app-install"
    xapian_base_path = "/var/cache/app-install"
    
    # set locale so that apt-ddtp stuff works
    locale.setlocale(locale.LC_ALL, "")

    pathname = os.path.join(xapian_base_path, "xapian")
    db = xapian.WritableDatabase(pathname, xapian.DB_CREATE_OR_OVERWRITE)
    cache = apt.Cache()
    update(db, cache, desktop_base_path)
