#!/usr/bin/python
# Copyright (C) 2009 Canonical
#
# Authors:
#  Michael Vogt
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA


import apt
import locale
import logging
import os
import sys
import xapian

try:
    from softwarestore.enums import *
except ImportError:
    # support running from the dir too
    d = os.path.dirname(os.path.abspath(os.path.join(os.getcwd(),__file__)))
    sys.path.insert(0, os.path.split(d)[0])
    from softwarestore.enums import *

try:
    from softwarestore.update_utils import DesktopConfigParser, update
except ImportError:
    # support running from the dir too
    d = os.path.dirname(os.path.abspath(os.path.join(os.getcwd(),__file__)))
    sys.path.insert(0, os.path.split(d)[0])
    from softwarestore.update_utils import DesktopConfigParser, update

if __name__ == "__main__":
    #logging.basicConfig(level=logging.DEBUG)

    try:
        locale.setlocale(locale.LC_ALL, "")
    except Exception, e:
        logging.exception("setlocale failed")

    xapian_base_path = XAPIAN_BASE_PATH
    
    # set locale so that apt-ddtp stuff works
    locale.setlocale(locale.LC_ALL, "")

    pathname = os.path.join(xapian_base_path, "xapian")
    if not os.path.exists(pathname):
        os.makedirs(pathname)
    db = xapian.WritableDatabase(pathname, xapian.DB_CREATE_OR_OVERWRITE)
    cache = apt.Cache(memonly=True)
    update(db, cache)
